apiVersion: v1
kind: Service
metadata:
  name: {{ include "client-stack.fullname" . }}-api
  labels:
    {{- include "client-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "client-stack.name" . }}
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}

