apiVersion: v1
kind: Service
metadata:
  name: {{ include "client-stack.fullname" . }}-postgres
  labels:
    {{- include "client-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "client-stack.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}

